### ISSUE TITLE
[Tracker] Tasks after switching to AWS

### ISSUE THREAD

**Issue by glogiotatidis** [mozilla/kitsune#3090]
- [x] Enable robots.txt #3082 
- [x] Enable email sending #3089
- [x] Set `READ_ONLY=False` #3091
- [x] Set `OIDC_ENABLE=True`
