### ISSUE TITLE
Remove traces of TravisCI from the project

### ISSUE THREAD

**Issue by finn0** [mozilla/kitsune#4507]
### Todo

- [ ] Remove scripts related to TravisCI in `./scripts/travis` folder.
- [ ] `./scripts/create_user_and_superuser.py` has dependence on TravisCI. In line [L#20](https://github.com/mozilla/kitsune/blob/master/scripts/create_user_and_superuser.py#L20), this script reads content of `./scripts/travis/variables.json`.
- [ ] Update [test.rst#create-test-users](https://github.com/mozilla/kitsune/blob/master/docs/tests.rst#create-test-users) document.

**Comment by du403** [comment]
![image](https://user-images.githubusercontent.com/66687336/91645820-d90e6200-ea16-11ea-81a6-cf5528a88029.jpg)
![50E47BEC-90C0-4D08-B94D-63B2E5EAB1D3](https://user-image#4516 #.githubusercontent.com/66687336/91645832-e9264180-ea16-11ea-867e-ca2d9fd209c2.jpeg)
#
![946B9BE3-36D2-42CF-AFB7-EE72B84D1630](https://user-images.githubusercontent.com/66687336/91645833-eb889b80-ea16-11ea-9600-35b32559c278.jpeg)
